name: tox

on:
  pull_request:
  push:
    branches: [master]

jobs:
  tox:
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install tox
      run: pip install --upgrade pip setuptools tox virtualenv
    - name: run tox
      run: tox -e py
